name: HalaTodo-API Dev Pull Request

on:
  pull_request:
    types: [ opened, reopened ]
    branches: [ dev ]

jobs:
  ESLint_Test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: npm install
      - name: ESLint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Slack Notification on SUCCESS
        if: ${{ success() }}
        uses: tokorom/action-slack-incoming-webhook@main
        env:
            INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
            text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|HalaTodo Pre-Check Succeed::${{ env.GITHUB_REF_SLUG }}>*'
            attachments: |
                [
                  {
                    "title": "사전 검증이 성공하였습니다.",
                    "text": "↑ PR LINK",
                    "title_link": "${{ github.event.repository.html_url }}/pull/${{ github.event.number }}",
                    "color": "good",
                    "author_name": "${{ github.actor }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}"
                  }
                ]

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: tokorom/action-slack-incoming-webhook@main
        env:
            INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
            text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|HalaTodo Pre-Check Failure::${{ env.GITHUB_REF_SLUG }}>*'
            attachments: |
                [
                  {
                    "title": "사전 검증에 실패하였습니다.",
                    "text": "↑ PR LINK",
                    "title_link": "${{ github.event.repository.html_url }}/pull/${{ github.event.number }}",
                    "color": "danger",
                    "author_name": "${{ github.actor }}",
                    "author_icon": "${{ github.event.sender.avatar_url }}"
                  }
                ]
        
